@url = http://localhost:8080/api/resellerOrg

GET {{url}} HTTP/1.1

###

GET {{url}}/2 HTTP/1.1

###

POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "name": "MCSS",
    "parentOrgId": 4,
    "childOrgId": null
}

###

PUT {{url}}/8 HTTP/1.1
Content-Type: application/json

{
    "name": "MCSS",
    "parentOrgId": 2,
    "childOrgId": 1,
    "resellerOrgId": 8
}

###

DELETE {{url}}/8 HTTP/1.1